version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - internal_bank_network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - internal_bank_network

  bank_db:
    image: postgres:15
    environment:
      POSTGRES_DB: banco_db
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: JhairV2002
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_bank_network
      
  nexus:
    image: sonatype/nexus3:latest
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - internal_bank_network

  # Microservicio de Persona
  ms-persona:
    build:
      context: ./ms-core-persona-cliente
      dockerfile: Dockerfile
      args:
        - NEXUS_USERNAME=admin
        - NEXUS_PASSWORD=Nacer500300
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bank_db:5432/banco_db
      - SPRING_DATASOURCE_USERNAME=bank
      - SPRING_DATASOURCE_PASSWORD=JhairV2002
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - bank_db
      - kafka
    networks:
      - internal_bank_network

  # Microservicio de Cuentas y Movimientos
  ms-cuentas-movimientos:
    build:
      context: ./ms-core-fin-cuentas-movimientos
      dockerfile: Dockerfile
      args:
        - NEXUS_USERNAME=admin
        - NEXUS_PASSWORD=Nacer500300
    ports:
      - "8081:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bank_db:5432/banco_db
      - SPRING_DATASOURCE_USERNAME=bank
      - SPRING_DATASOURCE_PASSWORD=JhairV2002
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - bank_db
      - kafka
    networks:
      - internal_bank_network

volumes:
  postgres_data:
  nexus_data:
  

networks:
  internal_bank_network:
    driver: bridge
